=== LiWinston/mybatis/mybatis-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT configuration (dataSource?, transaction?, mappers?, plugins?, typeAliases?, typeHandlers?, objectFactory?)>

        <!ELEMENT typeAliases (typeAlias*)>

        <!ELEMENT typeAlias EMPTY>
        <!ATTLIST typeAlias
                type CDATA #REQUIRED
                alias CDATA #IMPLIED
                >

        <!ELEMENT typeHandlers (typeHandler*)>
        <!ELEMENT typeHandler EMPTY>
        <!ATTLIST typeHandler
                javaType CDATA #REQUIRED
                jdbcType CDATA #IMPLIED
                handler CDATA #REQUIRED
                >

        <!ELEMENT objectFactory (#PCDATA)>
        <!ATTLIST objectFactory
                type CDATA #REQUIRED
                >

        <!ELEMENT plugins (plugin+)>
        <!ELEMENT plugin (#PCDATA)>
        <!ATTLIST plugin
                interceptor CDATA #REQUIRED
                >

        <!ELEMENT dataSource (property*)>
        <!ATTLIST dataSource
                type CDATA #IMPLIED
                >
        <!ELEMENT property EMPTY>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT transaction (property*)>
        <!ATTLIST transaction type (jdbc|manage) "manage">

        <!ELEMENT mappers (mapper*)>
        <!ELEMENT mapper EMPTY>
        <!ATTLIST mapper
                resource CDATA #IMPLIED
                url CDATA #IMPLIED
                class CDATA #IMPLIED
                >

=== LiWinston/mybatis/src/test/resources/mybatis-config-8-0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration
        PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
        "mybatis-config.dtd">
<configuration>

    <dataSource>
        <property name="driver" value="com.mysql.cj.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&amp;serverTimezone=UTC&amp;useSSL=false"/>
        <property name="username" value="root"/>
        <property name="password" value="lyc980820"/>
    </dataSource>

    <transaction type="jdbc">
        <property name="autoCommit" value="true"/>
        <property name="isolationLevel" value="READ_UNCOMMITTED"/>
    </transaction>

    <mappers>
        <mapper resource="mapper/UserMapper.xml"/>
    </mappers>

    <plugins>
        <plugin interceptor="com.github.houbb.mybatis.plugin.SimpleLogInterceptor"/>
    </plugins>

    <typeHandlers>
        <typeHandler javaType="date" handler="com.github.houbb.mybatis.typehandler.DateTypeHandler"/>
    </typeHandlers>

    <objectFactory type="com.github.houbb.mybatis.support.MyObjectFactory"/>

</configuration>
